name: Check compilation on tree-sitter 0.19

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: cp package-json-old-tree-sitter.json package.json
    - run: npm install
    - run: npx tree-sitter test -f "Does not match any named tests; only runs queries."
